version: '3.8'

services: 
  php-apache-environment:
    build:
        context: ./
        dockerfile: Dockerfile.dockerfile
    container_name: php-apache
    restart: always
    depends_on:
        - db
    volumes:
        - ./infs3200proj:/var/www/html/proj
    ports:
        - "8080:80"
    networks: 
        - mynet 

  db:
    image: mysql
    container_name: db
    restart: always
    environment: 
      MYSQL_ROOT_PASSWORD: MYSQL_ROOT_PASSWORD
      MYSQL_DATABASE: MY_DATABASE
      MYSQL_USER: MYSQL_USER
      MYSQL_PASSWORD: MYSQL_PASSWORD
    ports:
      - "3306:3306"
    networks: 
      - mynet 

networks:
    mynet:
        driver: bridge
