version: '3.8'

services: 
  php-apache-environment:
    build:
        context: ./php
        dockerfile: Dockerfile.dockerfile
    container_name: php-apache
    restart: always
    depends_on:
        - db
    volumes:
        - ./php/src/myProj/:/var/www/html/
    ports:
        - "80:80"
    networks: 
        - mynet 

  db:
    image: mysql:latest
    container_name: db
    restart: always
    environment: 
      MYSQL_ROOT_PASSWORD: MYSQL_ROOT_PASSWORD
      MYSQL_DATABASE: MY_DATABASE
      MYSQL_USER: MYSQL_USER
      MYSQL_PASSWORD: MYSQL_PASSWORD
    volumes: 
      - ./myProj.sql:/docker-entrypoint-initdb.d/myProj.sql
    ports:
      - "3306:3306"
    networks: 
      - mynet 

  phpMyAdmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    container_name: phpMyAdmin
    restart: always
    ports: 
      - "8082:80"
    environment: 
      PMA_HOST: db
    networks: 
      - mynet   

networks:
    mynet:
        driver: bridge
